export enum TipoPerfil {
  ADMIN = 'ADMIN',
  SECRETARIA = 'SECRETARIA',
  DIRETOR = 'DIRETOR',
  PROFESSOR = 'PROFESSOR',
  PAIS = 'PAIS',
  RESPONSAVEL = 'RESPONSAVEL',
  FINANCEIRO = 'FINANCEIRO',
  COORDENADOR = 'COORDENADOR',
  FUNCIONARIO = 'FUNCIONARIO',
}
